name: SIG Table checking

on:
  pull_request:
  merge_group:

jobs:
  table-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: verify SIG tables in README.md
        run: make table-check
