name: SIG Table checking

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  table-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: verify SIG tables in README.md
        run: make table-check
