name: SIG Table checking

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  table-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: verify SIG tables in README.md
        run: make table-check
