name: SIG Table checking

on:
  pull_request:
  merge_group:

jobs:
  table-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: verify SIG tables in README.md
        run: make table-check
